const temp = {
  requestAppInfos: [
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/Required_Update',
      'name': 'Update_Required_v2',
      'version': '0.0.2',
      'blacklist': false,
      'remove': false,
      'description': 'Requierd Update Test WebApp',
      'short_name': 'Update_Required_v2',
      'file_size': 16586,
      'filename': 'diff_000000002_000000002_1527814616134.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/Required_Update/icon/icon_1527814616047.png'
    },
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/kaolafm',
      'name': 'KaolaFM',
      'version': '0.0.18',
      'blacklist': false,
      'required': false,
      'background': false,
      'remove': false,
      'description': `Koala FM is China's largest Internet radio, providing popular Internet radio programs.`,
      'short_name': 'KaolaFM',
      'new': 'OPTION',
      'file_size': 352428,
      'filename': 'diff_000000018_000000018_1526621635473.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/kaolafm/icon/icon_1526621635360.png'
    },
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/Native_Install',
      'name': 'Native Install_v1',
      'version': '0.0.1',
      'blacklist': false,
      'required': false,
      'background': false,
      'remove': false,
      'description': 'Native Install_v1',
      'short_name': 'Native Install_v1',
      'new': 'OPTION',
      'file_size': 1360610,
      'filename': 'diff_000000001_000000001_1527813721507.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/Native_Install/icon/icon_1527813721303.png'
    },
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/Native_Required_Update',
      'name': 'Native Required_v2',
      'version': '0.0.2',
      'blacklist': false,
      'required': true,
      'background': true,
      'remove': false,
      'description': 'Native Required_v2',
      'short_name': 'Native Required_v2',
      'new': 'OPTION',
      'file_size': 1360566,
      'filename': 'diff_000000002_000000002_1527813962909.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/Native_Required_Update/icon/icon_1527813962792.png'
    },
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/Native_Update',
      'name': 'Update_v2',
      'version': '0.0.2',
      'blacklist': false,
      'required': false,
      'background': false,
      'remove': false,
      'description': 'Update_v2',
      'short_name': 'Update_v2',
      'new': 'OPTION',
      'file_size': 1359999,
      'filename': 'diff_000000002_000000002_1527814115447.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/Native_Update/icon/icon_1527814115332.png'
    },
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/Install',
      'name': 'Install_v1',
      'version': '0.0.1',
      'blacklist': false,
      'required': false,
      'background': false,
      'remove': false,
      'description': 'Install_v1',
      'short_name': 'Install_v1',
      'new': 'OPTION',
      'file_size': 16554,
      'filename': 'diff_000000001_000000001_1527814391059.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/Install/icon/icon_1527814390972.png'
    },
    {
      'id': 'http://www.obigo.com/DYK/QEPIO/Update',
      'name': 'Update_v2',
      'version': '0.0.2',
      'blacklist': false,
      'required': false,
      'background': false,
      'remove': false,
      'description': 'Update_v2',
      'short_name': 'Update_v2',
      'new': 'OPTION',
      'file_size': 16560,
      'filename': 'diff_000000002_000000002_1527814543505.wgt',
      'app_icon': 'https://dykappcenter.obigo.com/lge/file/Update/icon/icon_1527814543399.png'
    }
  ],
  widgets: [
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: 'Home for various applications. You can enjoy and explore the variety of apps in your car!',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true }, { "name": "http://www.obigo.com/api/developer", "required": true }, { "name": "http://www.obigo.com/api/SVG", "required": true }, { "name": "http://www.obigo.com/api/telephony", "required": true } ] }`,
      group: 'launcher',
      iconHeight: 110,
      iconSrcPath: 'icon_1527813962792.png',
      iconWidth: 110,
      id: 'http://www.obigo.com/ssangyong/C300/launcher',
      installTime: '1528078301',
      license: 'Obigo Licence',
      licenseHref: '',
      localURI: 'https://dykappcenter.obigo.com/lge/file/Native_Required_Update/icon/',
      nameList: `{ "widgetName": [ { "name": "U+ 서비스 메인", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "launcher", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.4',
      widgetHeight: 650,
      widgetWidth: 1280
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: '홈IoT 서비스를 제공합니다.',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/network", "required": true }, { "name": "http://www.obigo.com/api/ai", "required": true }, { "name": "http://www.obigo.com/api/cloud", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/ssangyong/C300/homeiot',
      installTime: '1528078301',
      license: 'Obigo',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_ssangyong_c300_homeiot_1528950221/',
      nameList: `{ "widgetName": [ { "name": "홈IoT", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "홈IoT", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.5',
      widgetHeight: 423,
      widgetWidth: 800
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: '국내 최다 음원 보유, FLAC 고음질, 지니차트, 최신음악, 앨범, 뮤직비디오, 오늘의 선곡, TV속음악, 시대별음악, 지니라이프 등 제공.',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/network", "required": true }, { "name": "http://www.obigo.com/api/audio", "required": true }, { "name": "http://www.obigo.com/api/ai", "required": true }, { "name": "http://www.obigo.com/api/cloud", "required": true }, { "name": "http://www.obigo.com/api/cluster", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true }, { "name": "http://www.obigo.com/api/telephony", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/ssangyong/C300/genie-music',
      installTime: '1528078302',
      license: 'Obigo',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_ssangyong_c300_genie_music_1529202292/',
      nameList: `{ "widgetName": [ { "name": "지니뮤직 플레이어", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "지니뮤직", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.10',
      widgetHeight: 423,
      widgetWidth: 800
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: 'Home for various applications. You can enjoy and explore the variety of apps in your car!',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/audio", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/posco/digen/vtuner',
      installTime: '1528078347',
      license: 'THE SOFTWARE IS PROVIDED BY OBIGO.',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_posco_digen_vtuner_1536163746/',
      nameList: `{ "widgetName": [ { "name": "vTuner", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "vTuner", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.0.0',
      widgetHeight: 423,
      widgetWidth: 800
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: 'Test1 서비스를 제공합니다.',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/network", "required": true }, { "name": "http://www.obigo.com/api/ai", "required": true }, { "name": "http://www.obigo.com/api/cloud", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/ssangyong/C300/test1',
      installTime: '1528078301',
      license: 'Obigo',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_ssangyong_c300_homeiot_1528950221/',
      nameList: `{ "widgetName": [ { "name": "Test1", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "Test1", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.5',
      widgetHeight: 423,
      widgetWidth: 800
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: 'Test2 서비스를 제공합니다.',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/network", "required": true }, { "name": "http://www.obigo.com/api/ai", "required": true }, { "name": "http://www.obigo.com/api/cloud", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/ssangyong/C300/test2',
      installTime: '1528078301',
      license: 'Obigo',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_ssangyong_c300_homeiot_1528950221/',
      nameList: `{ "widgetName": [ { "name": "Test2", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "Test2", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.5',
      widgetHeight: 423,
      widgetWidth: 800
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: 'Test3 서비스를 제공합니다.',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/network", "required": true }, { "name": "http://www.obigo.com/api/ai", "required": true }, { "name": "http://www.obigo.com/api/cloud", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/ssangyong/C300/test3',
      installTime: '1528078301',
      license: 'Obigo',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_ssangyong_c300_homeiot_1528950221/',
      nameList: `{ "widgetName": [ { "name": "Test3", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "Test3", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.5',
      widgetHeight: 423,
      widgetWidth: 800
    },
    {
      activationDate: 0,
      activationStatus: true,
      authorEmail: '',
      authorHref: '',
      authorName: 'Obigo',
      autostart: false,
      category: '',
      description: 'Test4 서비스를 제공합니다.',
      expirationDate: 0,
      expired: false,
      featureList: `{ "feature": [ { "name": "http://www.obigo.com/api/applicationmanager.getownerapplication", "required": true }, { "name": "http://www.obigo.com/api/storage", "required": true }, { "name": "http://www.obigo.com/api/network", "required": true }, { "name": "http://www.obigo.com/api/ai", "required": true }, { "name": "http://www.obigo.com/api/cloud", "required": true }, { "name": "http://www.obigo.com/api/serviceAgent", "required": true } ] }`,
      group: '',
      iconHeight: 0,
      iconSrcPath: 'icon.png',
      iconWidth: 0,
      id: 'http://www.obigo.com/ssangyong/C300/test4',
      installTime: '1528078301',
      license: 'Obigo',
      licenseHref: '',
      localURI: 'file:///home/oad/OAD/OAF/AFAsset/apps/contents/private/http___www_obigo_com_ssangyong_c300_homeiot_1528950221/',
      nameList: `{ "widgetName": [ { "name": "Test4", "lang": "en-us" } ] }`,
      reserved: true,
      running: true,
      service: false,
      shortNameList: `{ "widgetShortName": [ { "name": "Test4", "lang": "en-us" } ] }`,
      subscriptionStatus: 0,
      version: '1.4.5',
      widgetHeight: 423,
      widgetWidth: 800
    }
  ],
  response: {
    RESPONSE_VERSION: {
      "DESTINATION": "UPDATER",
      "MSG": {
        "SOFTWARELIST": [
          {
            "BACKGROUND": false,
            "BLACKLIST": false,
            "DESCRIPTION": "Ver 1.4.10",
            "FILE_SIZE":4847929,
            "ICON":"https://dykappcenter.obigo.com/lge/file/weather/icon/icon_1528449111830.png",
            "ID":"http://www.obigo.com/ssangyong/C300/weather",
            "NAME":"Weather",
            "REMOVE":false,
            "REQUIRED":false,
            "SHORT_NAME":"Weather",
            "VERSION":"1.4.10"
          }
        ]
      },
      "MSG_TYPE":"RESPONSE_VERSION",
      "SOURCE":"APDS",
      "SUBTIME":"1528697160248",
      "TIME":"1528772948824"
    },
    RESPONSE_DOWNLOADED_LIST: {
      "DESTINATION": "APPLICATION",
      "MSG": {"SOFTWARELIST":[]},
      "MSG_TYPE": "RESPONSE_DOWNLOADED_LIST",
      "SOURCE": "UPDATER",
      "SUBTIME": "1528794399424",
      "TIME": "1528794399"
    }
  }
}

export default temp
