const downloadManagerError = {
  Type: {
    DOWNLOAD_ERROR_SUCCESS: 0, // 에러 없이 정상적으로 수행
    DOWNLOAD_ERROR_UNKNOWN: 1, // 알수 없는 에러
    DOWNLOAD_ERROR_NETWORK_UNREACHABLE: 2, // 네트웍에 연결되어 있지 않는 상태
    DOWNLOAD_ERROR_CONNECT_FAIL: 100, // 연결 실패
    DOWNLOAD_ERROR_CONNECT_NOT: 101, // 연결이 없음
    DOWNLOAD_ERROR_CONNECT_TRYING: 102, // 연결중
    DOWNLOAD_ERROR_CONNECT_EXIST: 103, // 연결이 이미 존재
    DOWNLOAD_ERROR_CONNECT_LOSS: 104, // Connection Loss
    DOWNLOAD_ERROR_CONNECT_TIMEOUT: 105, // 서버 응답 시간 초과
    DOWNLOAD_ERROR_REQUEST_BAD: 200, // Request Format 오류
    DOWNLOAD_ERROR_REQUEST_TIMEOUT: 201, // 요청에 대한 Timeout
    DOWNLOAD_ERROR_REQUEST_INVALID_TOKEN: 202, // 유효하지 않은 Token으로 요청
    DOWNLOAD_ERROR_TOKEN_FAIL: 300, // TOKEN 요청이 실패
    DOWNLOAD_ERROR_TOKEN_INVALID_ID: 301, // 유효하지 않는 ID로 토큰 요청
    DOWNLOAD_ERROR_TOKEN_EXPIRED: 302, // 토큰의 유효기간 만료
    DOWNLOAD_ERROR_VERSION_FAIL: 400, // Version 정보 생성 실패
    DOWNLOAD_ERROR_VERSION_ERROR: 401, // Version 정보 오류
    DOWNLOAD_ERROR_DOWNLOAD_FAIL: 500, // DOWNLOAD 실패
    DOWNLOAD_ERROR_DOWNLOAD_NOT_EXIST: 501, // DOWNLOAD 관련 파일이 존재하지 않음
    DOWNLOAD_ERROR_DOWNLOAD_TIMEOUT: 502, // DOWNLOAD 대기 시간 초과
    DOWNLOAD_ERROR_DOWNLOAD_DOING: 503, // 요청한 다운로드가 이미 수행 중
    DOWNLOAD_ERROR_FILE_FAIL: 600, // File 작업 수행 오류
    DOWNLOAD_ERROR_FILE_OPEN: 601, // File을 Open할 수 없음
    DOWNLOAD_ERROR_FILE_READ: 602, // File을 읽을 수 없음
    DOWNLOAD_ERROR_FILE_EXIST: 603, // File이 이미 존재함
    DOWNLOAD_ERROR_FILE_NOT_EXIST: 604, // File이 존재하지 않음
    DOWNLOAD_ERROR_FILE_WRITE: 605, // File을 Write 할 수 없음
    DOWNLOAD_ERROR_UPDATE_FAIL: 700, // Application Update 오류
    DOWNLOAD_ERROR_UPDATE_DOING: 701 // 업데이트를 수행 중
  },
  Code: {
    0: 'DOWNLOAD_ERROR_SUCCESS',
    1: 'DOWNLOAD_ERROR_UNKNOWN',
    2: 'DOWNLOAD_ERROR_NETWORK_UNREACHABLE',
    100: 'DOWNLOAD_ERROR_CONNECT_FAIL',
    101: 'DOWNLOAD_ERROR_CONNECT_NOT',
    102: 'DOWNLOAD_ERROR_CONNECT_TRYING',
    103: 'DOWNLOAD_ERROR_CONNECT_EXIST',
    104: 'DOWNLOAD_ERROR_CONNECT_LOSS',
    105: 'DOWNLOAD_ERROR_CONNECT_TIMEOUT',
    200: 'DOWNLOAD_ERROR_REQUEST_BAD',
    201: 'DOWNLOAD_ERROR_REQUEST_TIMEOUT',
    202: 'DOWNLOAD_ERROR_REQUEST_INVALID_TOKEN',
    300: 'DOWNLOAD_ERROR_TOKEN_FAIL',
    301: 'DOWNLOAD_ERROR_TOKEN_INVALID_ID',
    302: 'DOWNLOAD_ERROR_TOKEN_EXPIRED',
    400: 'DOWNLOAD_ERROR_VERSION_FAIL',
    401: 'DOWNLOAD_ERROR_VERSION_ERROR',
    500: 'DOWNLOAD_ERROR_DOWNLOAD_FAIL',
    501: 'DOWNLOAD_ERROR_DOWNLOAD_NOT_EXIST',
    502: 'DOWNLOAD_ERROR_DOWNLOAD_TIMEOUT',
    503: 'DOWNLOAD_ERROR_DOWNLOAD_DOING',
    600: 'DOWNLOAD_ERROR_FILE_FAIL',
    601: 'DOWNLOAD_ERROR_FILE_OPEN',
    602: 'DOWNLOAD_ERROR_FILE_READ',
    603: 'DOWNLOAD_ERROR_FILE_EXIST',
    604: 'DOWNLOAD_ERROR_FILE_NOT_EXIST',
    605: 'DOWNLOAD_ERROR_FILE_WRITE',
    700: 'DOWNLOAD_ERROR_UPDATE_FAIL',
    701: 'DOWNLOAD_ERROR_UPDATE_DOING'
  }
}

export default downloadManagerError
