const msgType = {
  RESPONSE_TOKEN: 'RESPONSE_TOKEN',
  RESPONSE_AVN_VERSION: 'RESPONSE_AVN_VERSION',
  RESPONSE_VERSION: 'RESPONSE_VERSION',
  RESPONSE_DOWNLOAD: 'RESPONSE_DOWNLOAD',
  RESPONSE_DOWNLOAD_CANCEL: 'RESPONSE_DOWNLOAD_CANCEL',
  RESPONSE_DOWNLOADED_LIST: 'RESPONSE_DOWNLOADED_LIST',
  RESPONSE_INTEGRITY: 'RESPONSE_INTEGRITY'
}

export default msgType
