const notifyType = {
  NOTIFY_DOWNLOAD_BEGIN: 'NOTIFY_DOWNLOAD_BEGIN',
  NOTIFY_DOWNLOAD_PROGRESS: 'NOTIFY_DOWNLOAD_PROGRESS',
  NOTIFY_DOWNLOAD_END: 'NOTIFY_DOWNLOAD_END',
  NOTIFY_ERROR: 'NOTIFY_ERROR'
}

export default notifyType
