const widgetError = {
  Type: {
    WIDGET_INSTALLATION_STARTED: 0,
    WIDGET_INSTALLATION_COMPLETED: 1,
    WIDGET_INSTALLATION_FAILED: 2,
    WIDGET_UNINSTALLATION_STARTED: 3,
    WIDGET_UNINSTALLATION_COMPLETED: 4,
    WIDGET_UNINSTALLATION_FAILED: 5,
    WIDGET_INSTALLATION_UPDATE_STARTED: 6,
    WIDGET_INSTALLATION_UPDATE_COMPLETED: 7,
    WIDGET_INSTALLSTION_UPDATE_FAILED: 8,
    WIDGET_ERROR_STORAGE_AREA_FULL: 10, // target에 widget을 저장할 공간이 없을 경우 발생
    WIDGET_ERROR_DOWNLOAD: 11, // TBD
    WIDGET_ERROR_INVALID_ZIP_ARCHIVE: 12, // widget 파일이 wgt 파일이 아닐 경우 발생
    WIDGET_ERROR_INVALID_SIGNATURE: 13, // widget 파일의 유효성 검사 실패시 발생
    WIDGET_ERROR_GENERIC: 14, // 일반적인 error의 경우 발생
    WIDGET_ERROR_SIZE_EXCEEDED: 15, // TBD
    WIDGET_ERROR_INVALID_UPDATE: 16, // TBD
    WIDGET_ERROR_ALREADY_EXIST: 17, // 기존에 동일한 directory로 생성된 widget이 있을 경우 발생.
    WIDGET_ERROR_CANNOT_REMOVE: 18, // 현재 user에 install되어 있지 않는 widget 파일을 삭제하려고 할 때 발생
    WIDGET_ERROR_APP_COUNT_FULL: 19, // install 할 수 있는 최대 개수를 넘어서 widget을 install하려고 할 때 발생.
    WIDGET_ERROR_INVALID_CONFIGURATION: 20, // 인증서 directory를 찾을 수 없거나, widget의 config.xml 에 오류가 있을 경우 발생.
    WIDGET_ERROR_INVALID_POLICY: 21, // AF policy 정책을 적용할 수 없는 경우 발생.
    WIDGET_ERROR_INVALID_FEATURE: 22, // TBD
    WIDGET_ERROR_INVALID_API_VERSION: 23, // widget 에서 사용하는 feature들의 version이 맞지 않을 경우 발생.
    WIDGET_ERROR_INVALID_PERMISSION: 24 // user가 application을 uninstall할 때, 권한이 없을 경우 발생
  },
  Code: {
    0: 'WIDGET_INSTALLATION_STARTED',
    1: 'WIDGET_INSTALLATION_COMPLETED',
    2: 'WIDGET_INSTALLATION_FAILED',
    3: 'WIDGET_UNINSTALLATION_STARTED',
    4: 'WIDGET_UNINSTALLATION_COMPLETED',
    5: 'WIDGET_UNINSTALLATION_FAILED',
    6: 'WIDGET_INSTALLATION_UPDATE_STARTED',
    7: 'WIDGET_INSTALLATION_UPDATE_COMPLETED',
    8: 'WIDGET_INSTALLSTION_UPDATE_FAILED',
    10: 'WIDGET_ERROR_STORAGE_AREA_FULL',
    11: 'WIDGET_ERROR_DOWNLOAD',
    12: 'WIDGET_ERROR_INVALID_ZIP_ARCHIVE',
    13: 'WIDGET_ERROR_INVALID_SIGNATURE',
    14: 'WIDGET_ERROR_GENERIC',
    15: 'WIDGET_ERROR_SIZE_EXCEEDED',
    16: 'WIDGET_ERROR_INVALID_UPDATE',
    17: 'WIDGET_ERROR_ALREADY_EXIST',
    18: 'WIDGET_ERROR_CANNOT_REMOVE',
    19: 'WIDGET_ERROR_APP_COUNT_FULL',
    20: 'WIDGET_ERROR_INVALID_CONFIGURATION',
    21: 'WIDGET_ERROR_INVALID_POLICY',
    22: 'WIDGET_ERROR_INVALID_FEATURE',
    23: 'WIDGET_ERROR_INVALID_API_VERSION',
    24: 'WIDGET_ERROR_INVALID_PERMISSIO'
  }
}

export default widgetError
